version: "3"
services:
  api:
    container_name: clean-node
    image: node:18
    restart: always
    working_dir: /usr/src/clean-node-api
    command: bash -c "npm install --only=prod && npm run debug"
    volumes:
      - ./dist:/usr/src/clean-node-api/dist
      - ./package.json:/usr/src/clean-node-api/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27018
    networks:
      - clean-node-network
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ~/data:/data/db
    ports:
      - "27018:27017"
    networks:
      - clean-node-network
networks:
  clean-node-network:
    driver: bridge
    
